### ISSUE TITLE
choose a SQL DB for release-2

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-js#38]
current candidates are: 

- PostgreSQL
- CockroachDB: https://www.cockroachlabs.com/
- Noria: https://github.com/mit-pdos/noria

we first need to go through a release cycle with release-1 to see what the load/requirements are and if any additional requirements will arise

also this will be useful for updating the event aggregates from multiple threads: https://github.com/jonhoo/rust-evmap

another important factor for this is the existance of a mature Rust driver with async IO

**Comment by elpiel** [comment]
After checking the 3 current candidates, but also took a look in general the library drivers and databases in Rust.
* Noria requires ZooKeeper & nightly, but as discussed, we do need Nightly for `async/await` and futures compact layer
* CockroachDB can be used with [sfackler/rust-postgres](https://github.com/sfackler/rust-postgres) driver, but there are some differences and even [diesel-rs](https://github.com/diesel-rs/diesel) doesn't officially supports CockroachDB atm. They even thing it should have a separate backend instead of [hacking into the postgres one](https://github.com/diesel-rs/diesel/issues/1667#issuecomment-385248841).
* The other DBs I've taken a look at are primarily key-value stores and don't even have a Rust driver(e.g. TiKV) or no `async/await` support, good overview of them can be found in [here in rust-unofficial/awesome-rust](https://github.com/rust-unofficial/awesome-rust#database-1)

The safest bet is still on PostgresSQL with the [sfackler/rust-postgres](https://github.com/sfackler/rust-postgres) as it also supports async/await

**Comment by Ivshti** [comment]
It was decided on Postgres cause of the good Rust driver
